pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'java11'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'Jenkins', url: 'https://github.com/GunaranjanV/devops_engineer.git'
            }
        }

        stage('Maven Clean') {
            steps {
                sh 'mvn clean'
            }
        }

        stage('Build Maven') {
            steps {
                sh 'mvn install'
            }
        }
    }
}