pipeline {
    agent any
    tools {
        maven 'Maven'
        jdk 'java11'
    }
    stages{
        stage('Git checkout'){
            steps{
                git branch: 'Jenkins', url: 'https://github.com/GunaranjanV/devops_engineer.git'
                
            }
        }    
        stage('Build Maven'){
            steps{
                sh 'mvn clean install'
            }
        }
    }
}